### ISSUE TITLE
package.json main js 指向错误

### ISSUE THREAD

**Issue by mice33** [BenzLeung/benz-audio-engine#1]
import benzAudioEngine from 'benz-audio-engine';

使用 import 导入插件时，因为 package.json main 指向的  src/benzAudioEngine.js，因为是源代码未转换 ES5，会有问题。

package.json main 应指向于转换 ES5 后根目录的 benzAudioEngine.js

**Comment by BenzLeung** [comment]
@mice33 谢谢指正！已经修正，同时也发布到了 npm 以方便使用。
我写这个的时候并不太会用 npm ，见谅啊~
